config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:password]
  resources :users, only: [:index, :edit, :update]
  root "tasks#index"
  resources :tasks
  get "/by_user/", to: "tasks#tasks_by_user", as: "tasks_by_user"
  get "/all_users_tasks/", to: "tasks#all_users_tasks", as: "all_users_tasks"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  extend ActiveModel::Naming
  extend Enumerize

  belongs_to :user, optional: true

  enumerize :status,
            in: { todo: 1, inprogress: 2, done: 3 },
            default: :todo,
            predicates: true

  validates :title, presence: { message: 'Title blank' }
  validates :title, length: { minimum: 5, message: 'Title min 5 chars' }
  validates :description, presence: { message: 'Description blank' }
  validates :description, length: { minimum: 10, message: 'Description min 10 chars' }

  scope :filter_by_status, ->(status, user_id) { where status: status, user_id: user_id }
  scope :filter_by_user_id, ->(user_id) { where user_id: user_id }
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveModel::Naming
  extend Enumerize

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy

  enumerize :role,
            in: { user: 1, admin: 2 },
            default: :user,
            predicates: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authorization
  include Pagy::Backend
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index; end

  def do_auth
    if !Admin.find_by(email: params[:email]).nil?
      redirect_to new_admin_session_path
    elsif !User.find_by(email: params[:email]).nil?
      redirect_to new_user_session_path
    else
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern
  included do
    include Pundit::Authorization
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  end

  private

  def user_not_authorized
    flash[:alert] = 'Sorry, You Are Not Authorized To Do This'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit update destroy]
  before_action :authorize_task

  def index
    @pagy, @tasks = pagy(fetch_tasks_service[:tasks])
    flash.now[:notice] = fetch_tasks_service[:msg] if fetch_tasks_service[:msg].present?
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params.merge({ user_id: current_user.id }))
    if @task.save
      flash[:notice] = 'Task successfully created'
      redirect_to @task
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    redirect_to_all_tasks if @task.nil?
  end

  def edit
    redirect_to_all_tasks if @task.nil?
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'Task successfully edited'
      redirect_to @task
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    flash[:notice] = 'Task successfully deleted'
    redirect_to tasks_path, status: :see_other
  end

  private

  def fetch_tasks_service
    Tasks::TasksFetchService.new(current_user, params).call
  end

  def redirect_to_all_tasks
    redirect_to tasks_path
    flash[:alert] = 'Task not exist'
  end

  def task_params
    params.require(:task).permit(:title, :description, :status)
  end

  def set_task
    @task = Task.find_by(id: params[:id])
  end

  def authorize_task
    authorize(@task || Task.new)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[edit update]
  before_action :authorize_user

  def index
    @users = User.all
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Profile successfully updated'
      redirect_to edit_user_path @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def authorize_user
    authorize(@user || User)
  end

  def user_params
    if current_user.admin?
      params.require(:user).permit(:email, :first_name, :last_name, :role)
    else
      params.require(:user).permit(:first_name, :last_name)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def form_errors_helper(obj, column)
    render partial: 'layouts/errors', locals: { obj: obj, column: column } if obj.errors.where(column).any?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def time_until_edit(task)
    time = task.created_at + 2.hours
    local_time(time, :time)
  end

  def index_page_tasks_list_empty(_tasks)
    link_to 'Create new task', new_task_path, class: 'btn btn btn-outline-primary' if current_user.tasks.empty?
  end

  def sort_reverse_button
    if params[:sort_status] == 'asc'
      link_to ' Sort by status', tasks_path(sort_status: 'desc'),
              class: 'btn btn-sm btn-outline-info ms-1 bi bi-arrow-down-up'
    else
      link_to ' Sort by status', tasks_path(sort_status: 'asc'),
              class: 'btn btn-sm btn-outline-info ms-1 bi bi-arrow-down-up'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<div class="alert-danger rounded-bottom p-1">
  <%obj.errors.where(column).each do |error|%>
    <div>
      <%=error.message%>
    </div>
  <%end%>
</div>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <p class="alert alert-success text-center"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger text-center"><%= alert %></p>
<% end %>

app/views/layouts/_login_links.html.erb
<%if !current_user%>
  <li class="nav-item"><%=link_to 'LogIn', new_user_session_path, class: 'nav-link active'%></li>
<%else current_user.present?%>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <%=current_user.email%>
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%=link_to "Edit profile", edit_user_path(current_user), class:"dropdown-item"%>
      <li><hr class="dropdown-divider"></li>
      <li><%=link_to 'LogOut',  destroy_user_session_path, 
                                data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' }, class: 'dropdown-item'%></li>
    </ul>
  </li>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top shadow navbar-expand-xxl navbar-light bg-light">
  <div class="container-fluid">
    <%=link_to "TodoApp", root_path, class: "navbar-brand fs-4"%>
    <%if current_user.present?%>
      <%=link_to " New task", new_task_path, class: "btn btn btn-outline-primary m-1 bi bi-plus-circle"%>
    <%end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%if current_user.present?%>
          <ul class="navbar-nav ms-2 p-1 ">
            <%=link_to " All tasks", tasks_path, class: "btn btn-sm btn-outline-primary ms-1 bi bi-list-task"%>
            <%=sort_reverse_button%>
            <%=link_to " Todo tasks", tasks_path(status: 'todo'), 
                                              class: "btn btn-sm btn-outline-info ms-1 bi bi-circle"%>
            <%=link_to " In progress tasks", tasks_path(status: 'inprogress'), 
                                              class: "btn btn-sm btn-outline-info ms-1 bi bi-hourglass-split"%>
            <%=link_to " Done tasks", tasks_path(status: 'done'),
                                              class: "btn btn-sm btn-outline-info ms-1 bi bi-check-circle-fill"%>
          </ul>
          <%if current_user.admin?%>
            <%=form_with url: tasks_path, method: :get do |f|%>
              <div class="input-group p-1">
                <%= f.collection_select :user_id, User.order(:id), :id, :email,
                 { promt: false, selected: params[:user_id] || current_user.id}, {class: "form-select form-select-sm"}  %>
                <%=f.button "Show", class: "btn btn-outline-secondary"%>
              </div>
            <%end%>
            <%=link_to " All users tasks", tasks_path(all_users_tasks: 'show'), class: "btn btn-outline-secondary ms-1 bi bi-people"%>
            <%=link_to " All users", users_path, class: "btn btn-outline-secondary ms-1 bi bi-people"%>
          <%end%>
        <%end%>
      </ul>
      <ul class="navbar-nav">
        <%=render partial: "layouts/login_links"%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%=render partial: "layouts/navbar"%>
    <%=render partial: "layouts/flashes"%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form_task.html.erb
<div class="col-lg-8 mx-auto bg-light shadow rounded-1 p-3 mt-5">
  <%= form_with model: @task do |f| %>
    <div class="mb-1">
      <%= f.label :title, class: "form-label fs-3" %>
    </div>
    <div class="mb-1">
      <%= f.text_field :title, autofocus: true, class: "form-control bg-light", style:" text-align: center" %>
    </div>
    <%=form_errors_helper(@task,:title)%>
    <div class="mb-1">
      <%= f.label :descrition, class: "form-label fs-3"  %>
    </div>
    <div class="mb-1">
      <%= f.text_area :description, size: "50x5", class: "form-control bg-light", style:" text-align: center" %>
    </div>
    <%=form_errors_helper(@task,:description)%>
    <div class="mb-1">
    </div>
    <%if @task.new_record?%>
      <div class="mb-1 mt-3">
        <%= f.submit "Create", class: "btn btn-primary fs-4 w-100" %>
      </div>
    <%else%>
      <div class="mb-1 ">
        <%= f.select :status, [["To do!", "todo"], ["In progress", "inprogress"], ["Done", "done"]],
                          {}, {class: "form-select form-select-lg mb-1 mt-3"}  %>
      </div>
      <div class="mb-1 mt-3">
        <%= f.submit "Save", class: "btn btn-primary fs-4 w-100" %>
      </div>
    <%end%>
  <%end%>
</div>

app/views/tasks/_index_tasks.html.erb
<div class="row align-items-center mt-4">
  <%=index_page_tasks_list_empty(@tasks)%>
  <%@tasks.each do |task|%>
    <div class="cards">
      <div class="card shadow mb-1 mt-1 bg-light p-1 ">
        <div class="cart-title fs-3 text-center w-50 mx-auto text-truncate">
          <%=task.title%>
        </div>
        <div class="fs-3 text-end">
          <%=render partial: "status",locals: {task: task}%>
        </div>
        <div class="cart-body">
          <div class="text-secondary">
            created by : <%=task.user.email%> <%=link_to "", task_path(task), class:"stretched-link "%>,
            at : <%=local_time(task.created_at, :long)%>
          </div>
        </div>
      </div>
    </div>
  <%end%>
  <%if @pagy.pages > 1%>
    <div class="container pagination justify-content-center border-top mt-3">
      <div class="mt-2">
        <%== pagy_bootstrap_nav(@pagy)  %>
      </div>
    </div>
  <%end%>
</div>

app/views/tasks/_status.html.erb
<%= 'Todo! <i class="bi bi-circle text-primary"></i>'.html_safe if task.status.todo? %>
<%='In progress ... <i class="bi bi-hourglass-split text-warning"></i>'.html_safe if task.status.inprogress? %>
<%='Done! <i class="bi bi-check-circle-fill text-success"></i>'.html_safe if task.status.done? %>

app/views/tasks/all_users_tasks.html.erb
<%=render partial: "index_tasks"%>

app/views/tasks/edit.html.erb
<h1 class="text-center">Edit task</h1>
<%=render partial: "form_task"%>

app/views/tasks/index.html.erb
<div class="row align-items-center mt-4">
  <%=index_page_tasks_list_empty(@tasks)%>
  <%@tasks.each do |task|%>
    <div class="card shadow mb-1 mt-1 bg-light">
      <div class=" cart-title fs-4 ">
        <%=task.title%>
        <div class="text-end">
          <%=render partial: "status",locals: {task: task}%>
        </div>
      </div>
      <div class=" cart-body  ">
        <div class=" ">
          created by : <%=task.user.email%> <%=link_to "", task_path(task), class:"stretched-link"%>
        </div>
      </div>
    </div>
  <%end%>
  <%if @pagy.pages > 1%>
    <div class="container pagination justify-content-center border-top mt-3">
      <div class="mt-2">
        <%== pagy_bootstrap_nav(@pagy)  %>
      </div>
    </div>
  <%end%>
</div>

app/views/tasks/new.html.erb
<h1 class="text-center">Create new task</h1>
<%=render partial: "form_task"%>

app/views/tasks/show.html.erb
<div class="card text-center mt-4 bg-light">
  <div class="card-title text-truncate w-50 mx-auto mt-1 fs-3">
    <%=@task.title%>
    <p>
      <%=render partial: "status", locals: {task: @task}%>
    </p>
  </div>
  <div class="card-body">
    <div>
      <%=@task.description%>
    </div>
    <div class="text-secondary mt-5 border-bottom">
      Created by : <%=@task.user.email%>, at : <%=local_time(@task.created_at, :long)%>
    </div>
    <%if (@task.user == current_user && @task.created_at + 2.hours > Time.now) && current_user.user?%>
      <div class="mt-2">
        <%=link_to "Can edit until #{ time_until_edit(@task)}".html_safe, 
                                                          edit_task_path, class: "btn btn-outline-secondary "%>
      </div>
    <%end%>
    <%if current_user.role.admin?%>
      <div class="mt-2">
        <%=link_to "Edit ".html_safe, edit_task_path, class: "btn btn-outline-secondary "%>
        <%=link_to "Delete task", task_path, class: "btn btn-outline-danger",
                                data: { "turbo-method": :delete , turbo_confirm: "Delete task #{@task.title}?"}%>
      </div>
    <%end%>
  </div>
</div>

app/views/tasks/tasks_by_user.html.erb
<%=render partial: "index_tasks"%>

app/views/users/_role.html.erb
<%= 'Admin! <i class="bi bi bi-person-fill text-success"></i>'.html_safe if user.role.admin? %>
<%='User <i class="bi bi bi-person text-primary"></i>'.html_safe if user.role.user? %>

app/views/users/edit.html.erb
<div class="col-lg-8 mx-auto bg-light shadow rounded-1 p-3 mt-5">
  <%= form_with model: @user do |f| %>
    <div class="mb-1">
      <div class=" fs-3 text-end">
        <%=render partial: "role", locals: {user: @user}%>
      </div>
      <%= f.email_field :email, autofocus: true, class: "form-control bg-light",
                         disabled: !current_user.admin?, placeholder: "Email", style:" text-align: center" %>
    </div>
    <%=form_errors_helper(@user,:email)%>
    <div class="mb-1">
      <%= f.text_field :first_name, autofocus: true, class: "form-control bg-light", 
                                    placeholder: "First name", style:" text-align: center" %>
    </div>
    <%=form_errors_helper(@user,:first_name)%>
    <div class="mb-1">
      <%= f.text_field :last_name, autofocus: true, class: "form-control bg-light",
                                     placeholder: "Last name", style:" text-align: center" %>
    </div>
    <%=form_errors_helper(@user,:last_name)%>
    <%if current_user.admin?%>
      <div class="mb-1 ">
        <%= f.select :role, User.role.values, {},
                     {class: "form-select form-select-lg mb-1 mt-3",disabled: @user.id == current_user.id} %>
      </div>
    <%end%>
    <div class="mb-1 mt-3">
      <%= f.submit "Save", class: "btn btn-primary fs-4 w-100" %>
    </div>
  <%end%>
</div>

app/views/users/index.html.erb
<div class="row align-items-center mt-4">
  <%@users.each do |user|%>
    <div class="cards">
      <div class="card shadow mb-1 mt-1 bg-light">
        <div class=" cart-title fs-4 text-center text-truncate">
          <%=user.email%>
          <div class="text-center ">
            <%=render partial: "role",locals: {user: user}%>
          </div>
        </div>
        <div class="cart-body mb-2">
          <div class="text-center ">
            <%=link_to "Edit user", edit_user_path(user), class:"btn btn-outline-secondary"%>
            <%=link_to "Show tasks ( #{user.tasks.size} )", tasks_by_user_path+"?user_id=#{user.id}",
                                                                     class:"btn btn-outline-secondary"%>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class:"btn btn-outline-secondary" %>
<% end %>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class:"btn btn-outline-secondary"  %>
<% end %>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class:"btn btn-outline-secondary"  %>
<% end %>
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>